name: imageCollector
description: Image Collection for Collection of Image Data for Campus Management System.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  firebase_core: "0.5.2+1"
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  uuid: ^2.2.2
  flutter_spinkit:
  multi_image_picker: ^4.7.14
  flutter_absolute_path:
  firebase_image: ^0.3.0
  

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700